"""
This module is embedding generator for the project
Generates embeddings for different levels of chunks (metadata, summary, meeting)
"""

from typing import List, Dict
import numpy as np
from langchain_openai import OpenAIEmbeddings

import sys
from pathlib import Path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from src.chunking.chunker import ChunkMetadata
from config.settings import EMBEDDING_MODEL


class EmbeddingGenerator:
    """
    Embedding generator for hierarchical RAG system
    
    Supports:
    - Single text embedding (for queries)
    - Batch text embeddings (for indexing)
    - Different chunk levels (metadata, summary, meeting)
    """
    
    def __init__(self, model_name: str | None = None , **kwargs):
        """
        Initialize the embedding generator
        
        Args:
            model_name: Name of the embedding model (default: from settings)
            **kwargs: Additional arguments for OpenAIEmbeddings
        """
        self.model_name = model_name or EMBEDDING_MODEL
        
        # Initialize OpenAI embeddings
        self.embeddings = OpenAIEmbeddings(
            model=self.model_name,
            **kwargs
        )
    
    def generate_embedding(self, text: str) -> np.ndarray:
        """
        Generate embedding for a single text (for queries)

        Args:
            text: Input text to embed

        Returns:
            numpy array of embedding vector
        """
        embedding = self.embeddings.embed_query(text)
        return np.array(embedding)
    
    def generate_embeddings_batch(self, 
                                  texts: List[str], 
                                  batch_size: int = 100) -> List[np.ndarray]:
        """
        Generate embeddings for a batch of texts (for indexing)

        Args:
            texts: List of input texts to embed
            batch_size: Batch size for embedding generation (default: 100)

        Returns:
            List of numpy arrays of embedding vectors
        """
        all_embeddings = []
        
        # Process in batches
        for i in range(0, len(texts), batch_size):
            batch_texts = texts[i:i + batch_size]
            
            # Generate embeddings for batch
            new_embeddings = self.embeddings.embed_documents(batch_texts)
            
            # Convert to numpy arrays
            for embedding in new_embeddings:
                all_embeddings.append(np.array(embedding))
        
        return all_embeddings
    
    def generate_chunks_embeddings(self, 
                                   chunks: List[ChunkMetadata],
                                   batch_size: int = 100) -> List[np.ndarray]:
        """
        Generate embeddings for a list of chunks (for indexing)

        Args:
            chunks: List of ChunkMetadata objects
            batch_size: Batch size for embedding generation (default: 100)

        Returns:
            List of numpy arrays of embedding vectors
        """
        texts = [chunk.text for chunk in chunks]
        return self.generate_embeddings_batch(texts, batch_size=batch_size)
    
    def generate_embeddings_by_level(self, 
                                     chunks_by_level: Dict[str, List[ChunkMetadata]],
                                     batch_size: int = 100) -> Dict[str, List[np.ndarray]]:
        """
        Generate embeddings for chunks organized by level
        
        Args:
            chunks_by_level: Dictionary with keys 'metadata', 'summary', 'meeting'
                            and values as lists of ChunkMetadata
            batch_size: Batch size for embedding generation (default: 100)
            
        Returns:
            Dictionary with same keys and values as lists of embedding vectors
        """
        result = {}
        
        for level, chunks in chunks_by_level.items():
            if chunks:
                print(f"Generating embeddings for {level} level: {len(chunks)} chunks...")
                result[level] = self.generate_chunks_embeddings(
                    chunks, 
                    batch_size=batch_size,
                )
            else:
                result[level] = []
        
        return result
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model
        
        Returns:
            Dimension of embedding vectors
        """
        # OpenAI embedding dimensions
        # text-embedding-ada-002: 1536
        # text-embedding-3-small: 1536
        # text-embedding-3-large: 3072
        
        model_dims = {
            'text-embedding-ada-002': 1536,
            'text-embedding-3-small': 1536,
            'text-embedding-3-large': 3072,
        }
        
        # Try to get from model name
        for model_name, dim in model_dims.items():
            if model_name in self.model_name.lower():
                return dim
        
        # Default: generate a test embedding to get dimension
        test_embedding = self.generate_embedding("test")
        return len(test_embedding)


# Testing code
if __name__ == "__main__":
    from src.data_loader.loader import DataLoader
    from src.chunking.chunker import HierarchicalChunker
    from config.settings import DATA_DIR
    
    # Load data
    print("Loading meetings...")
    loader = DataLoader(DATA_DIR)
    meetings = loader.load_all_meetings()
    
    if not meetings:
        print("No meetings found!")
        exit(1)
    
    # Chunk data
    print("\nChunking meetings...")
    chunker = HierarchicalChunker()
    all_chunks = chunker.chunk_all_levels(meetings)
    
    # Generate embeddings
    print("\nGenerating embeddings...")
    generator = EmbeddingGenerator()
    
    # Test single embedding
    test_chunk = all_chunks['metadata'][0] if all_chunks['metadata'] else None
    if test_chunk:
        print(f"\nTesting single embedding for chunk: {test_chunk.chunk_id}")
        embedding = generator.generate_embedding(test_chunk.text)
        print(f"Embedding shape: {embedding.shape}")
        print(f"Embedding dimension: {generator.get_embedding_dimension()}")
    
    # Test batch embeddings
    print(f"\nGenerating batch embeddings...")
    all_texts = []
    all_chunks_list = []
    for level, chunks in all_chunks.items():
        all_texts.extend([chunk.text for chunk in chunks])
        all_chunks_list.extend(chunks)
    
    embeddings = generator.generate_embeddings_batch(all_texts)
    
    # Print statistics
    print("\n" + "="*80)
    print("EMBEDDING GENERATION STATISTICS")
    print("="*80)
    for level, chunks in all_chunks.items():
        level_embeddings = [emb for emb, chunk in zip(embeddings, all_chunks_list) if chunk.level == level]
        print(f"  {level.capitalize()} level: {len(level_embeddings)} embeddings")
        if level_embeddings:
            print(f"    - Embedding dimension: {level_embeddings[0].shape[0]}")
    print("="*80)
