"""
Phase 2 Evaluation Script — Evaluate Adapter Predictions

Designed to run locally (no GPU required).
Reads predictions.jsonl generated by predict_test_set.py and evaluates using:
  1. Schema Compliance (automatic)
  2. Preservation Rate (automatic)
  3. LLM-as-a-Judge (GPT-4o, reference-free, 3 sub-dimensions)

Usage:
    python evaluate_phase2.py
    python evaluate_phase2.py --predictions path/to/predictions.jsonl
    python evaluate_phase2.py --skip-judge   # Auto metrics only, no API cost
"""

import json
import os
import sys
import math
import argparse
import logging
import datetime
from pathlib import Path
from typing import Dict, List, Any, Tuple

# Add project root for potential config imports
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from openai import OpenAI

# Fix SSL cert issue (mirrors project convention)
if "SSL_CERT_FILE" in os.environ:
    cert_path = os.environ["SSL_CERT_FILE"]
    if cert_path and not os.path.exists(cert_path):
        del os.environ["SSL_CERT_FILE"]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)


# ==========================================
# Constants — Preference Schema Definition
# ==========================================
REQUIRED_TOP_KEYS = {"communication_style", "scheduling", "focus_areas"}
COMM_STYLE_KEYS = {"language", "length", "format", "tone"}
SCHEDULING_KEYS = {"preferred_times", "unavailable_times"}


# ==========================================
# LLM Judge Prompt (Reference-Free)
# ==========================================
JUDGE_SYSTEM_PROMPT = """\
You are an expert evaluator for a preference extraction model used in a meeting assistant.

Your task: Given a user's current preferences, new evidence (conversation or meeting text),
and the model's predicted updated preferences, evaluate the prediction quality.

IMPORTANT: You are judging whether the prediction is REASONABLE, not whether it matches
a specific "correct" answer. Multiple valid interpretations of the same evidence are acceptable.

Score on 3 dimensions (1-5 each):

1. Signal Detection
   - 5: Correctly identified all preference signals in the evidence
        (or correctly recognized NO signals in neutral/everyday text)
   - 3: Identified some signals but missed others, or detected ambiguous signals
   - 1: Completely missed obvious signals, or hallucinated signals that don't exist

2. Value Assignment
   - 5: All assigned values are correct and well-justified by the evidence
   - 3: Some values are reasonable but others are debatable or slightly off
   - 1: Values clearly contradict the evidence

3. Completeness
   - 5: Every preference signal in the evidence is reflected in the output
   - 3: Some signals captured, others missed
   - 1: Most signals missed

Special case — neutral evidence (no preference signals):
If the evidence is ordinary conversation with NO preference signals, the correct behavior
is to output preferences IDENTICAL to the current preferences.
- Score 5 on all dimensions if the model correctly preserved everything unchanged.
- Score 1 if the model changed preferences when it should not have.

Output ONLY a valid JSON object with no extra text:
{"signal_detection": <int 1-5>, "value_assignment": <int 1-5>, "completeness": <int 1-5>, "reasoning": "<one sentence explanation>"}
"""


# ==========================================
# Metric 1: Schema Compliance
# ==========================================
def check_schema_compliance(predicted: Dict) -> Tuple[bool, List[str]]:
    """
    Verify that the predicted JSON has the complete preference schema skeleton.
    Returns (is_valid, list_of_errors).
    """
    errors = []

    # Top-level keys
    missing_top = REQUIRED_TOP_KEYS - set(predicted.keys())
    if missing_top:
        errors.append(f"Missing top-level keys: {missing_top}")

    # communication_style sub-keys
    cs = predicted.get("communication_style")
    if isinstance(cs, dict):
        missing_cs = COMM_STYLE_KEYS - set(cs.keys())
        if missing_cs:
            errors.append(f"communication_style missing: {missing_cs}")
    else:
        errors.append(f"communication_style is not a dict (got {type(cs).__name__})")

    # scheduling sub-keys
    sched = predicted.get("scheduling")
    if isinstance(sched, dict):
        missing_sched = SCHEDULING_KEYS - set(sched.keys())
        if missing_sched:
            errors.append(f"scheduling missing: {missing_sched}")
    else:
        errors.append(f"scheduling is not a dict (got {type(sched).__name__})")

    # focus_areas must be a list
    fa = predicted.get("focus_areas")
    if not isinstance(fa, list):
        errors.append(f"focus_areas is not a list (got {type(fa).__name__})")

    return len(errors) == 0, errors


# ==========================================
# Metric 2: Preservation Rate
# ==========================================
def check_preservation(
    current_prefs: Dict,
    predicted: Dict,
    target_field: str,
    scenario: str,
) -> Tuple[bool, List[str]]:
    """
    Verify that non-target fields are preserved unchanged from current_preferences.
    For nochange scenario, ALL fields must be preserved.
    Returns (is_valid, list_of_errors).
    """
    errors = []

    # Determine which fields should be preserved
    if scenario == "no_change":
        fields_to_check = list(REQUIRED_TOP_KEYS)
    else:
        fields_to_check = [f for f in REQUIRED_TOP_KEYS if f != target_field]

    for field in fields_to_check:
        current_val = current_prefs.get(field)
        predicted_val = predicted.get(field)

        if current_val != predicted_val:
            cur_str = json.dumps(current_val, ensure_ascii=False)[:120]
            pred_str = json.dumps(predicted_val, ensure_ascii=False)[:120]
            errors.append(f"'{field}' changed: {cur_str} → {pred_str}")

    return len(errors) == 0, errors


# ==========================================
# Metric 3: LLM-as-a-Judge (Reference-Free)
# ==========================================
def judge_with_llm(
    client: OpenAI,
    current_prefs: str,
    evidence: str,
    predicted: str,
    model: str = "gpt-4o",
) -> Dict[str, Any]:
    """
    Use GPT-4o to evaluate the predicted preferences in a reference-free manner.
    The Judge only sees (current_prefs, evidence, predicted) — no ground truth.
    Returns dict with signal_detection, value_assignment, completeness, reasoning.
    """
    user_prompt = (
        "Evaluate the following preference extraction:\n\n"
        f"[Current Preferences]\n{current_prefs}\n\n"
        f"[New Evidence]\n{evidence}\n\n"
        f"[Model's Predicted Updated Preferences]\n{predicted}"
    )

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.0,
            max_tokens=300,
            response_format={"type": "json_object"},
        )
        result = json.loads(response.choices[0].message.content)
        return {
            "signal_detection": int(result.get("signal_detection", 0)),
            "value_assignment": int(result.get("value_assignment", 0)),
            "completeness": int(result.get("completeness", 0)),
            "reasoning": result.get("reasoning", ""),
        }
    except Exception as e:
        logger.error(f"  LLM Judge error: {e}")
        return {
            "signal_detection": 0,
            "value_assignment": 0,
            "completeness": 0,
            "reasoning": f"Error: {e}",
        }


# ==========================================
# Report Generation
# ==========================================
def generate_report(results: List[Dict], output_path: Path) -> str:
    """Generate a markdown evaluation report and save to file."""
    total = len(results)
    json_ok = sum(1 for r in results if r["json_parseable"])
    schema_ok = sum(1 for r in results if r["schema_valid"])
    pres_ok = sum(1 for r in results if r["preservation_valid"])

    # Judge aggregation (only for successfully judged samples)
    judged = [
        r for r in results
        if r.get("judge") and r["judge"]["signal_detection"] > 0
    ]

    if judged:
        avg_sig = sum(r["judge"]["signal_detection"] for r in judged) / len(judged)
        avg_val = sum(r["judge"]["value_assignment"] for r in judged) / len(judged)
        avg_cmp = sum(r["judge"]["completeness"] for r in judged) / len(judged)
        avg_all = (avg_sig + avg_val + avg_cmp) / 3
    else:
        avg_sig = avg_val = avg_cmp = avg_all = 0.0

    # Breakdown by scenario
    by_scenario: Dict[str, Dict[str, Any]] = {}
    for r in results:
        s = r["metadata"].get("scenario", "unknown")
        if s not in by_scenario:
            by_scenario[s] = {
                "total": 0, "schema": 0, "preservation": 0, "scores": [],
            }
        by_scenario[s]["total"] += 1
        if r["schema_valid"]:
            by_scenario[s]["schema"] += 1
        if r["preservation_valid"]:
            by_scenario[s]["preservation"] += 1
        if r.get("judge") and r["judge"]["signal_detection"] > 0:
            score = (
                r["judge"]["signal_detection"]
                + r["judge"]["value_assignment"]
                + r["judge"]["completeness"]
            ) / 3
            by_scenario[s]["scores"].append(score)

    # Build markdown
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Phase 2 Evaluation Report — Preference Extraction Adapter",
        "",
        f"> **Date**: {now}  ",
        f"> **Total Test Samples**: {total}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Metric | Score |",
        "|---|---|",
        f"| JSON Parseable | {json_ok}/{total} ({json_ok/total*100:.0f}%) |",
        f"| Schema Compliance | {schema_ok}/{total} ({schema_ok/total*100:.0f}%) |",
        f"| Preservation Rate | {pres_ok}/{total} ({pres_ok/total*100:.0f}%) |",
    ]

    if judged:
        lines.extend([
            f"| LLM Judge — Signal Detection | {avg_sig:.2f}/5 |",
            f"| LLM Judge — Value Assignment | {avg_val:.2f}/5 |",
            f"| LLM Judge — Completeness | {avg_cmp:.2f}/5 |",
            f"| **LLM Judge — Overall** | **{avg_all:.2f}/5** |",
        ])

    lines.extend([
        "",
        "---",
        "",
        "## Breakdown by Scenario",
        "",
        "| Scenario | Count | Schema | Preservation | Judge Avg |",
        "|---|---|---|---|---|",
    ])

    for s_name in sorted(by_scenario.keys()):
        d = by_scenario[s_name]
        j_avg = sum(d["scores"]) / len(d["scores"]) if d["scores"] else 0
        lines.append(
            f"| {s_name} | {d['total']} | {d['schema']}/{d['total']} | "
            f"{d['preservation']}/{d['total']} | {j_avg:.2f}/5 |"
        )

    # Flagged samples (failures or low scores)
    flagged = [
        r for r in results
        if not r["schema_valid"]
        or not r["preservation_valid"]
        or (
            r.get("judge")
            and r["judge"]["signal_detection"] > 0
            and (
                r["judge"]["signal_detection"]
                + r["judge"]["value_assignment"]
                + r["judge"]["completeness"]
            ) / 3 < 3
        )
    ]

    if flagged:
        lines.extend(["", "---", "", "## Flagged Samples (Need Review)", ""])
        for r in flagged:
            lines.append(f"### {r['id']}")
            lines.append("")
            if not r["json_parseable"]:
                raw = r["predicted_raw"][:200]
                lines.append(f"- ❌ **JSON Parse Failed**: `{raw}...`")
            if not r["schema_valid"]:
                lines.append(
                    f"- ❌ **Schema Errors**: {'; '.join(r['schema_errors'])}"
                )
            if not r["preservation_valid"]:
                lines.append(
                    f"- ❌ **Preservation Errors**: {'; '.join(r['preservation_errors'])}"
                )
            if r.get("judge") and r["judge"]["signal_detection"] > 0:
                avg = (
                    r["judge"]["signal_detection"]
                    + r["judge"]["value_assignment"]
                    + r["judge"]["completeness"]
                ) / 3
                if avg < 3:
                    lines.append(
                        f"- ⚠️ **Low Judge Score**: {avg:.1f}/5 — "
                        f"{r['judge']['reasoning']}"
                    )
            lines.append("")

    report = "\n".join(lines)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    return report


# ==========================================
# Main Pipeline
# ==========================================
def main():
    parser = argparse.ArgumentParser(
        description="Phase 2 Evaluation for Preference Extraction Adapter"
    )
    parser.add_argument(
        "--predictions",
        type=str,
        default=str(Path(__file__).parent.parent / "data" / "predictions.jsonl"),
        help="Path to predictions.jsonl generated by predict_test_set.py",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=str(
            Path(__file__).parent.parent / "data" / "phase2_evaluation_report.md"
        ),
        help="Path to output evaluation report (markdown)",
    )
    parser.add_argument(
        "--skip-judge",
        action="store_true",
        help="Skip LLM Judge (runs only automatic metrics, no API cost)",
    )
    parser.add_argument(
        "--judge-model",
        type=str,
        default="gpt-4o",
        help="OpenAI model for LLM Judge (default: gpt-4o)",
    )
    args = parser.parse_args()

    predictions_path = Path(args.predictions)
    output_path = Path(args.output)

    # Load predictions
    if not predictions_path.exists():
        logger.error(f"Predictions file not found: {predictions_path}")
        logger.error(
            "Run predict_test_set.py on Colab first to generate predictions."
        )
        sys.exit(1)

    with open(predictions_path, "r", encoding="utf-8") as f:
        predictions = [json.loads(line) for line in f if line.strip()]

    logger.info(f"Loaded {len(predictions)} predictions from {predictions_path}")

    # Initialize LLM Judge client
    client = None
    if not args.skip_judge:
        client = OpenAI()
        logger.info(f"LLM Judge enabled (model: {args.judge_model})")
    else:
        logger.info("LLM Judge SKIPPED (--skip-judge flag)")

    # Evaluate each prediction
    results = []
    for i, pred in enumerate(predictions):
        sample_id = pred["id"]
        metadata = pred.get("metadata", {})
        current_prefs_str = pred["current_preferences"]
        evidence = pred["new_evidence"]
        predicted_raw = pred["predicted"]
        target_field = metadata.get("field_type", "")
        scenario = metadata.get("scenario", "")

        result = {
            "id": sample_id,
            "metadata": metadata,
            "predicted_raw": predicted_raw,
            "json_parseable": False,
            "schema_valid": False,
            "schema_errors": [],
            "preservation_valid": False,
            "preservation_errors": [],
            "judge": None,
        }

        # --- Step 1: JSON Parseability ---
        try:
            predicted_json = json.loads(predicted_raw)
            result["json_parseable"] = True
        except json.JSONDecodeError:
            logger.warning(f"  [{sample_id}] ❌ JSON parse failed")
            results.append(result)
            continue

        # --- Step 2: Schema Compliance ---
        s_ok, s_errors = check_schema_compliance(predicted_json)
        result["schema_valid"] = s_ok
        result["schema_errors"] = s_errors

        # --- Step 3: Preservation ---
        try:
            current_json = json.loads(current_prefs_str)
        except json.JSONDecodeError:
            current_json = {}

        p_ok, p_errors = check_preservation(
            current_json, predicted_json, target_field, scenario
        )
        result["preservation_valid"] = p_ok
        result["preservation_errors"] = p_errors

        # --- Step 4: LLM Judge ---
        if client is not None:
            judge_result = judge_with_llm(
                client,
                current_prefs_str,
                evidence,
                predicted_raw,
                model=args.judge_model,
            )
            result["judge"] = judge_result
            avg = (
                judge_result["signal_detection"]
                + judge_result["value_assignment"]
                + judge_result["completeness"]
            ) / 3
            status = "✅" if avg >= 3 else "⚠️"
            logger.info(
                f"  [{i+1}/{len(predictions)}] {sample_id}: "
                f"schema={'✅' if s_ok else '❌'} "
                f"pres={'✅' if p_ok else '❌'} "
                f"judge={avg:.1f}/5 {status}"
            )
        else:
            logger.info(
                f"  [{i+1}/{len(predictions)}] {sample_id}: "
                f"schema={'✅' if s_ok else '❌'} "
                f"pres={'✅' if p_ok else '❌'}"
            )

        results.append(result)

    # Generate report
    print("\n" + "=" * 60)
    report = generate_report(results, output_path)
    print(report)
    print("=" * 60)
    logger.info(f"Report saved to {output_path}")


if __name__ == "__main__":
    main()
